#! /bin/sh
# startup daemons and programs
bsp-layout set even &
nitrogen --set-scaled /usr/share/backgrounds/archlinux/small.png
# Launch OpenTabledDriver
# otd-daemon &
# Bar, notifications, keyboard shortcuts
pgrep -x lemonbar > /dev/null || lemonbar -p &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
# If you need compositer
pgrep -X xcompmgr > /dev/null || xcompmgr &
# Workspaces
bspc monitor -d I II III IIII
# Bspwm Settings
bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
