#! /bin/sh
# startup daemons and programs
bsp-layout set even &
# Workspaces
bspc monitor -d I II III
# Bspwm Settings
bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
